.TH getpid 2  "May 21, 2010" "version 0.1" "System Calls"
.SH NAME
getpid \- get the PID of the current process
.SH SYNOPSIS
.B getpid
.SH DESCRIPTION
Get the PID of the current process.
.SH EXAMPLES
.TP
Get the PID of the current process:
.B getpid
.PP
.SH EXIT STATUS
Returns the PID of the current process.
