.TH getticks 2  "May 21, 2010" "version 0.1" "System Calls"
.SH NAME
getticks \- get the current system time, in ticks
.SH SYNOPSIS
.B getticks
.SH DESCRIPTION
Get the current system time, in ticks.
.SH EXAMPLES
.TP
Get the current system time:
.B getticks
.PP
.SH EXIT STATUS
Returns the current system time, in ticks.
