relfs_close

void relfs_close( relfs_t *fs );

.TH relfs_close 2  "May 21, 2010" "version 0.1" "System Calls"
.SH NAME
relfs_close \- closes the filesystem
.SH SYNOPSIS
.B relfs_close
fs
.SH DESCRIPTION
Closes the given filesystem.
.SH OPTIONS
.TP
fs
a pointer to the filesystem we want to close
